declare const self: ServiceWorkerGlobalScope;

// Precache list generated by build tool
const manifest = (self as any).__WB_MANIFEST || [];

self.addEventListener('install', (event: any) => {
  event.waitUntil(
    caches.open('hwms-v1').then((cache) => {
      const urls = manifest.map((entry: any) => typeof entry === 'string' ? entry : entry.url);
      return cache.addAll(urls);
    })
  );
});

self.addEventListener('fetch', (event: any) => {
  event.respondWith(
    caches.match(event.request).then((response) => {
      return response || fetch(event.request);
    })
  );
});

// Listen to incoming Web Push messages
self.addEventListener('push', (event: any) => {
  if (!event.data) return;

  try {
    const payload = event.data.json();
    const notification = payload.notification || {};
    const title = notification.title || 'HWMS Indotek';
    const options = {
      body: notification.body || '',
      icon: notification.icon || '/pwa-192x192.png',
      badge: '/pwa-192x192.png',
      data: {
        url: notification.data?.url || '/'
      }
    };

    event.waitUntil(
      self.registration.showNotification(title, options)
    );
  } catch (err) {
    console.error('Failed to parse push notification payload:', err);
  }
});

// Listen to notification click actions
self.addEventListener('notificationclick', (event: any) => {
  event.notification.close();
  const urlToOpen = new URL(event.notification.data?.url || '/', self.location.origin).href;

  event.waitUntil(
    self.clients.matchAll({ type: 'window', includeUncontrolled: true }).then((windowClients: any) => {
      for (const client of windowClients) {
        if (client.url === urlToOpen && 'focus' in client) {
          return client.focus();
        }
      }
      if (self.clients.openWindow) {
        return self.clients.openWindow(urlToOpen);
      }
    })
  );
});
